package com.panel;
import Database.*;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class ProductItem extends javax.swing.JPanel {
    
    private Product data;
    
    public void setData(Product data) {
        String price = data.getPrice().toString();
        nameContainer.setText(data.getName().toUpperCase());
        priceContainer.setText("$" + price);
        byte[] imgBlob = data.getImage(); 
        try {
            BufferedImage img = ImageIO.read(new ByteArrayInputStream(imgBlob));
            ImageIcon img2 = new ImageIcon(img);
            Image preparedImg = img2.getImage();
            Image preparedImg2 = preparedImg.getScaledInstance(100, 100, Image.SCALE_DEFAULT);
            ImageIcon image = new ImageIcon(preparedImg2);
            
            imageContainer.setIcon(image);
            
        } catch (IOException ex) {
            Logger.getLogger(ProductItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ProductItem() {
        initComponents();
        imageContainer.setPreferredSize(new Dimension(100, 100));  // Adjust width and height as needed
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageContainer = new javax.swing.JLabel();
        nameContainer = new javax.swing.JLabel();
        priceContainer = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        imageContainer.setBackground(new java.awt.Color(255, 153, 153));

        nameContainer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nameContainer.setForeground(new java.awt.Color(0, 0, 0));
        nameContainer.setText("productName");

        priceContainer.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        priceContainer.setForeground(new java.awt.Color(0, 0, 0));
        priceContainer.setText("productPrice");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameContainer)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(priceContainer)
                            .addComponent(imageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(imageContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameContainer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceContainer)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageContainer;
    private javax.swing.JLabel nameContainer;
    private javax.swing.JLabel priceContainer;
    // End of variables declaration//GEN-END:variables
}
